### ISSUE TITLE
How to Perform DPI (Deep Packet Inspection)

### ISSUE THREAD

**Issue by EsharkySignalZero** [geun-yeong/wfp-example#1]
Hi, I was following your wfpkm driver code and got it working! However I further want to print out the packets as well along with information about the direction of communication, ip address and ports. would you happen to know how to do this ?

I tried FwpsCopyStreamToBuffer but my code keeps crashing, is there any alternate way to this ?

**Comment by geun-yeong** [comment]
Sorry, I have not tried to copy packet stream in WPF driver.. I plan to update code if I know how to copy the stream
